package com.rainbowland.service.boot;

import com.rainbowland.service.AbstractServiceConfiguration;
import com.rainbowland.service.R2dbcProperties;
import com.rainbowland.service.characters.domain.*;
import io.r2dbc.spi.ConnectionFactory;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.core.convert.converter.Converter;
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate;
import org.springframework.r2dbc.connection.R2dbcTransactionManager;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.transaction.ReactiveTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.reactive.TransactionalOperator;

import java.util.ArrayList;
import java.util.List;

@Configurable
public class CharacterServiceConfiguration extends AbstractServiceConfiguration {

    @Bean
    @ConfigurationProperties("datasource.characters")
    public R2dbcProperties characterR2dbcProperties() {
        return new R2dbcProperties();
    }

    @Bean
    public ConnectionFactory characterConnectionFactory(@Qualifier("characterR2dbcProperties") R2dbcProperties properties) {
        return super.connectionFactory(properties);
    }

    @Bean
    public DatabaseClient characterDatabaseClient(@Qualifier("characterConnectionFactory") ConnectionFactory connectionFactory) {
        return super.databaseClient(connectionFactory);
    }
    @Bean
    public R2dbcEntityTemplate characterR2dbcEntityTemplate(@Qualifier("characterDatabaseClient") DatabaseClient databaseClient) {
        return super.r2dbcEntityTemplate(databaseClient);
    }

    @Override
    protected List<Converter<?, ?>> getCustomConverters() {
        List<Converter<?, ?>> converterList = new ArrayList<>();
        converterList.add(new AccountData.RowMapper());
        converterList.add(new AccountData.ParamMapper());
        converterList.add(new AccountInstanceTimes.RowMapper());
        converterList.add(new AccountInstanceTimes.ParamMapper());
        converterList.add(new AccountTutorial.RowMapper());
        converterList.add(new AccountTutorial.ParamMapper());
        converterList.add(new ArenaTeam.RowMapper());
        converterList.add(new ArenaTeam.ParamMapper());
        converterList.add(new ArenaTeamMember.RowMapper());
        converterList.add(new ArenaTeamMember.ParamMapper());
        converterList.add(new AuctionBidders.RowMapper());
        converterList.add(new AuctionBidders.ParamMapper());
        converterList.add(new AuctionItems.RowMapper());
        converterList.add(new AuctionItems.ParamMapper());
        converterList.add(new Auctionhouse.RowMapper());
        converterList.add(new Auctionhouse.ParamMapper());
        converterList.add(new BlackmarketAuctions.RowMapper());
        converterList.add(new BlackmarketAuctions.ParamMapper());
        converterList.add(new Bugreport.RowMapper());
        converterList.add(new Bugreport.ParamMapper());
        converterList.add(new CalendarEvents.RowMapper());
        converterList.add(new CalendarEvents.ParamMapper());
        converterList.add(new CalendarInvites.RowMapper());
        converterList.add(new CalendarInvites.ParamMapper());
        converterList.add(new Channels.RowMapper());
        converterList.add(new Channels.ParamMapper());
        converterList.add(new CharacterAccountData.RowMapper());
        converterList.add(new CharacterAccountData.ParamMapper());
        converterList.add(new CharacterAchievement.RowMapper());
        converterList.add(new CharacterAchievement.ParamMapper());
        converterList.add(new CharacterAchievementProgress.RowMapper());
        converterList.add(new CharacterAchievementProgress.ParamMapper());
        converterList.add(new CharacterAction.RowMapper());
        converterList.add(new CharacterAction.ParamMapper());
        converterList.add(new CharacterArenaStats.RowMapper());
        converterList.add(new CharacterArenaStats.ParamMapper());
        converterList.add(new CharacterAura.RowMapper());
        converterList.add(new CharacterAura.ParamMapper());
        converterList.add(new CharacterAuraEffect.RowMapper());
        converterList.add(new CharacterAuraEffect.ParamMapper());
        converterList.add(new CharacterAuraStoredLocation.RowMapper());
        converterList.add(new CharacterAuraStoredLocation.ParamMapper());
        converterList.add(new CharacterBanned.RowMapper());
        converterList.add(new CharacterBanned.ParamMapper());
        converterList.add(new CharacterBattlegroundData.RowMapper());
        converterList.add(new CharacterBattlegroundData.ParamMapper());
        converterList.add(new CharacterBattlegroundRandom.RowMapper());
        converterList.add(new CharacterBattlegroundRandom.ParamMapper());
        converterList.add(new CharacterCufProfiles.RowMapper());
        converterList.add(new CharacterCufProfiles.ParamMapper());
        converterList.add(new CharacterCurrency.RowMapper());
        converterList.add(new CharacterCurrency.ParamMapper());
        converterList.add(new CharacterCustomizations.RowMapper());
        converterList.add(new CharacterCustomizations.ParamMapper());
        converterList.add(new CharacterDeclinedname.RowMapper());
        converterList.add(new CharacterDeclinedname.ParamMapper());
        converterList.add(new CharacterEquipmentsets.RowMapper());
        converterList.add(new CharacterEquipmentsets.ParamMapper());
        converterList.add(new CharacterFavoriteAuctions.RowMapper());
        converterList.add(new CharacterFavoriteAuctions.ParamMapper());
        converterList.add(new CharacterFishingsteps.RowMapper());
        converterList.add(new CharacterFishingsteps.ParamMapper());
        converterList.add(new CharacterGarrison.RowMapper());
        converterList.add(new CharacterGarrison.ParamMapper());
        converterList.add(new CharacterGarrisonBlueprints.RowMapper());
        converterList.add(new CharacterGarrisonBlueprints.ParamMapper());
        converterList.add(new CharacterGarrisonBuildings.RowMapper());
        converterList.add(new CharacterGarrisonBuildings.ParamMapper());
        converterList.add(new CharacterGarrisonFollowerAbilities.RowMapper());
        converterList.add(new CharacterGarrisonFollowerAbilities.ParamMapper());
        converterList.add(new CharacterGarrisonFollowers.RowMapper());
        converterList.add(new CharacterGarrisonFollowers.ParamMapper());
        converterList.add(new CharacterGifts.RowMapper());
        converterList.add(new CharacterGifts.ParamMapper());
        converterList.add(new CharacterGlyphs.RowMapper());
        converterList.add(new CharacterGlyphs.ParamMapper());
        converterList.add(new CharacterHomebind.RowMapper());
        converterList.add(new CharacterHomebind.ParamMapper());
        converterList.add(new CharacterInstance.RowMapper());
        converterList.add(new CharacterInstance.ParamMapper());
        converterList.add(new CharacterInventory.RowMapper());
        converterList.add(new CharacterInventory.ParamMapper());
        converterList.add(new CharacterPet.RowMapper());
        converterList.add(new CharacterPet.ParamMapper());
        converterList.add(new CharacterPetDeclinedname.RowMapper());
        converterList.add(new CharacterPetDeclinedname.ParamMapper());
        converterList.add(new CharacterPvpTalent.RowMapper());
        converterList.add(new CharacterPvpTalent.ParamMapper());
        converterList.add(new CharacterQueststatus.RowMapper());
        converterList.add(new CharacterQueststatus.ParamMapper());
        converterList.add(new CharacterQueststatusDaily.RowMapper());
        converterList.add(new CharacterQueststatusDaily.ParamMapper());
        converterList.add(new CharacterQueststatusMonthly.RowMapper());
        converterList.add(new CharacterQueststatusMonthly.ParamMapper());
        converterList.add(new CharacterQueststatusObjectives.RowMapper());
        converterList.add(new CharacterQueststatusObjectives.ParamMapper());
        converterList.add(new CharacterQueststatusObjectivesCriteria.RowMapper());
        converterList.add(new CharacterQueststatusObjectivesCriteria.ParamMapper());
        converterList.add(new CharacterQueststatusObjectivesCriteriaProgress.RowMapper());
        converterList.add(new CharacterQueststatusObjectivesCriteriaProgress.ParamMapper());
        converterList.add(new CharacterQueststatusRewarded.RowMapper());
        converterList.add(new CharacterQueststatusRewarded.ParamMapper());
        converterList.add(new CharacterQueststatusSeasonal.RowMapper());
        converterList.add(new CharacterQueststatusSeasonal.ParamMapper());
        converterList.add(new CharacterQueststatusWeekly.RowMapper());
        converterList.add(new CharacterQueststatusWeekly.ParamMapper());
        converterList.add(new CharacterReputation.RowMapper());
        converterList.add(new CharacterReputation.ParamMapper());
        converterList.add(new CharacterSkills.RowMapper());
        converterList.add(new CharacterSkills.ParamMapper());
        converterList.add(new CharacterSocial.RowMapper());
        converterList.add(new CharacterSocial.ParamMapper());
        converterList.add(new CharacterSpell.RowMapper());
        converterList.add(new CharacterSpell.ParamMapper());
        converterList.add(new CharacterSpellCharges.RowMapper());
        converterList.add(new CharacterSpellCharges.ParamMapper());
        converterList.add(new CharacterSpellCooldown.RowMapper());
        converterList.add(new CharacterSpellCooldown.ParamMapper());
        converterList.add(new CharacterStats.RowMapper());
        converterList.add(new CharacterStats.ParamMapper());
        converterList.add(new CharacterTalent.RowMapper());
        converterList.add(new CharacterTalent.ParamMapper());
        converterList.add(new CharacterTransmogOutfits.RowMapper());
        converterList.add(new CharacterTransmogOutfits.ParamMapper());
        converterList.add(new CharacterVoidStorage.RowMapper());
        converterList.add(new CharacterVoidStorage.ParamMapper());
        converterList.add(new Characters.RowMapper());
        converterList.add(new Characters.ParamMapper());
        converterList.add(new Corpse.RowMapper());
        converterList.add(new Corpse.ParamMapper());
        converterList.add(new CorpseCustomizations.RowMapper());
        converterList.add(new CorpseCustomizations.ParamMapper());
        converterList.add(new CorpsePhases.RowMapper());
        converterList.add(new CorpsePhases.ParamMapper());
        converterList.add(new CreatureRespawn.RowMapper());
        converterList.add(new CreatureRespawn.ParamMapper());
        converterList.add(new GameEventConditionSave.RowMapper());
        converterList.add(new GameEventConditionSave.ParamMapper());
        converterList.add(new GameEventSave.RowMapper());
        converterList.add(new GameEventSave.ParamMapper());
        converterList.add(new GameobjectRespawn.RowMapper());
        converterList.add(new GameobjectRespawn.ParamMapper());
        converterList.add(new GmBug.RowMapper());
        converterList.add(new GmBug.ParamMapper());
        converterList.add(new GmComplaint.RowMapper());
        converterList.add(new GmComplaint.ParamMapper());
        converterList.add(new GmComplaintChatlog.RowMapper());
        converterList.add(new GmComplaintChatlog.ParamMapper());
        converterList.add(new GmSuggestion.RowMapper());
        converterList.add(new GmSuggestion.ParamMapper());
        converterList.add(new GroupInstance.RowMapper());
        converterList.add(new GroupInstance.ParamMapper());
        converterList.add(new GroupMember.RowMapper());
        converterList.add(new GroupMember.ParamMapper());
        converterList.add(new Groups.RowMapper());
        converterList.add(new Groups.ParamMapper());
        converterList.add(new Guild.RowMapper());
        converterList.add(new Guild.ParamMapper());
        converterList.add(new GuildAchievement.RowMapper());
        converterList.add(new GuildAchievement.ParamMapper());
        converterList.add(new GuildAchievementProgress.RowMapper());
        converterList.add(new GuildAchievementProgress.ParamMapper());
        converterList.add(new GuildBankEventlog.RowMapper());
        converterList.add(new GuildBankEventlog.ParamMapper());
        converterList.add(new GuildBankItem.RowMapper());
        converterList.add(new GuildBankItem.ParamMapper());
        converterList.add(new GuildBankRight.RowMapper());
        converterList.add(new GuildBankRight.ParamMapper());
        converterList.add(new GuildBankTab.RowMapper());
        converterList.add(new GuildBankTab.ParamMapper());
        converterList.add(new GuildEventlog.RowMapper());
        converterList.add(new GuildEventlog.ParamMapper());
        converterList.add(new GuildFinderApplicant.RowMapper());
        converterList.add(new GuildFinderApplicant.ParamMapper());
        converterList.add(new GuildFinderGuildSettings.RowMapper());
        converterList.add(new GuildFinderGuildSettings.ParamMapper());
        converterList.add(new GuildMember.RowMapper());
        converterList.add(new GuildMember.ParamMapper());
        converterList.add(new GuildMemberWithdraw.RowMapper());
        converterList.add(new GuildMemberWithdraw.ParamMapper());
        converterList.add(new GuildNewslog.RowMapper());
        converterList.add(new GuildNewslog.ParamMapper());
        converterList.add(new GuildRank.RowMapper());
        converterList.add(new GuildRank.ParamMapper());
        converterList.add(new Instance.RowMapper());
        converterList.add(new Instance.ParamMapper());
        converterList.add(new InstanceReset.RowMapper());
        converterList.add(new InstanceReset.ParamMapper());
        converterList.add(new InstanceScenarioProgress.RowMapper());
        converterList.add(new InstanceScenarioProgress.ParamMapper());
        converterList.add(new ItemInstance.RowMapper());
        converterList.add(new ItemInstance.ParamMapper());
        converterList.add(new ItemInstanceArtifact.RowMapper());
        converterList.add(new ItemInstanceArtifact.ParamMapper());
        converterList.add(new ItemInstanceArtifactPowers.RowMapper());
        converterList.add(new ItemInstanceArtifactPowers.ParamMapper());
        converterList.add(new ItemInstanceAzerite.RowMapper());
        converterList.add(new ItemInstanceAzerite.ParamMapper());
        converterList.add(new ItemInstanceAzeriteEmpowered.RowMapper());
        converterList.add(new ItemInstanceAzeriteEmpowered.ParamMapper());
        converterList.add(new ItemInstanceAzeriteMilestonePower.RowMapper());
        converterList.add(new ItemInstanceAzeriteMilestonePower.ParamMapper());
        converterList.add(new ItemInstanceAzeriteUnlockedEssence.RowMapper());
        converterList.add(new ItemInstanceAzeriteUnlockedEssence.ParamMapper());
        converterList.add(new ItemInstanceGems.RowMapper());
        converterList.add(new ItemInstanceGems.ParamMapper());
        converterList.add(new ItemInstanceModifiers.RowMapper());
        converterList.add(new ItemInstanceModifiers.ParamMapper());
        converterList.add(new ItemInstanceTransmog.RowMapper());
        converterList.add(new ItemInstanceTransmog.ParamMapper());
        converterList.add(new ItemLootItems.RowMapper());
        converterList.add(new ItemLootItems.ParamMapper());
        converterList.add(new ItemLootMoney.RowMapper());
        converterList.add(new ItemLootMoney.ParamMapper());
        converterList.add(new ItemRefundInstance.RowMapper());
        converterList.add(new ItemRefundInstance.ParamMapper());
        converterList.add(new ItemSoulboundTradeData.RowMapper());
        converterList.add(new ItemSoulboundTradeData.ParamMapper());
        converterList.add(new LfgData.RowMapper());
        converterList.add(new LfgData.ParamMapper());
        converterList.add(new Mail.RowMapper());
        converterList.add(new Mail.ParamMapper());
        converterList.add(new MailItems.RowMapper());
        converterList.add(new MailItems.ParamMapper());
        converterList.add(new PetAura.RowMapper());
        converterList.add(new PetAura.ParamMapper());
        converterList.add(new PetAuraEffect.RowMapper());
        converterList.add(new PetAuraEffect.ParamMapper());
        converterList.add(new PetSpell.RowMapper());
        converterList.add(new PetSpell.ParamMapper());
        converterList.add(new PetSpellCharges.RowMapper());
        converterList.add(new PetSpellCharges.ParamMapper());
        converterList.add(new PetSpellCooldown.RowMapper());
        converterList.add(new PetSpellCooldown.ParamMapper());
        converterList.add(new Petition.RowMapper());
        converterList.add(new Petition.ParamMapper());
        converterList.add(new PetitionSign.RowMapper());
        converterList.add(new PetitionSign.ParamMapper());
        converterList.add(new PoolQuestSave.RowMapper());
        converterList.add(new PoolQuestSave.ParamMapper());
        converterList.add(new PvpstatsBattlegrounds.RowMapper());
        converterList.add(new PvpstatsBattlegrounds.ParamMapper());
        converterList.add(new PvpstatsPlayers.RowMapper());
        converterList.add(new PvpstatsPlayers.ParamMapper());
        converterList.add(new QuestTracker.RowMapper());
        converterList.add(new QuestTracker.ParamMapper());
        converterList.add(new ReservedName.RowMapper());
        converterList.add(new ReservedName.ParamMapper());
        converterList.add(new Updates.RowMapper());
        converterList.add(new Updates.ParamMapper());
        converterList.add(new UpdatesInclude.RowMapper());
        converterList.add(new UpdatesInclude.ParamMapper());
        converterList.add(new WardenAction.RowMapper());
        converterList.add(new WardenAction.ParamMapper());
        converterList.add(new Worldstates.RowMapper());
        converterList.add(new Worldstates.ParamMapper());

        return converterList;
    }


}
