package com.github.mmo.game.map.enums;

public enum SpawnObjectTypeMask {

    SPAWN_TYPEMASK_CREATURE =(1<<SPAWN_TYPE_CREATURE),
    SPAWN_TYPEMASK_GAMEOBJECT =(1<<SPAWN_TYPE_GAMEOBJECT),
    SPAWN_TYPEMASK_AREATRIGGER =(1<<SPAWN_TYPE_AREATRIGGER),

    SPAWN_TYPEMASK_WITH_DATA =(1<<NUM_SPAWN_TYPES_WITH_DATA)-1,
    SPAWN_TYPEMASK_ALL =(1<<NUM_SPAWN_TYPES)-1
}
