package com.rainbowland.enums;

// Spell mechanics
public enum Mechanics {
    MECHANIC_NONE,
    MECHANIC_CHARM,
    MECHANIC_DISORIENTED,
    MECHANIC_DISARM,
    MECHANIC_DISTRACT,
    MECHANIC_FEAR,
    MECHANIC_GRIP,
    MECHANIC_ROOT,
    MECHANIC_SLOW_ATTACK,
    MECHANIC_SILENCE,
    MECHANIC_SLEEP,
    MECHANIC_SNARE,
    MECHANIC_STUN,
    MECHANIC_FREEZE,
    MECHANIC_KNOCKOUT,
    MECHANIC_BLEED,
    MECHANIC_BANDAGE,
    MECHANIC_POLYMORPH,
    MECHANIC_BANISH,
    MECHANIC_SHIELD,
    MECHANIC_SHACKLE,
    MECHANIC_MOUNT,
    MECHANIC_INFECTED,
    MECHANIC_TURN,
    MECHANIC_HORROR,
    MECHANIC_INVULNERABILITY,
    MECHANIC_INTERRUPT,
    MECHANIC_DAZE,
    MECHANIC_DISCOVERY,
    MECHANIC_IMMUNE_SHIELD, // Divine (Blessing) Shield/Protection and Ice Block
    MECHANIC_SAPPED,
    MECHANIC_ENRAGED,
    MECHANIC_WOUNDED,
    MAX_MECHANIC
}
