package com.rainbowland.enums;

public enum PetNameInvalidReason {
    // custom), not send
    PET_NAME_SUCCESS,

    PET_NAME_INVALID,
    PET_NAME_NO_NAME,
    PET_NAME_TOO_SHORT,
    PET_NAME_TOO_LONG,
    PET_NAME_MIXED_LANGUAGES,
    PET_NAME_PROFANE,
    PET_NAME_RESERVED,
    PET_NAME_THREE_CONSECUTIVE,
    PET_NAME_INVALID_SPACE,
    PET_NAME_CONSECUTIVE_SPACES,
    PET_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS,
    PET_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END,
    PET_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME
}
