package com.github.azeroth.dbc.defines;

public enum CharSectionType {
    SECTION_TYPE_SKIN_LOW_RES,
    SECTION_TYPE_FACE_LOW_RES,
    SECTION_TYPE_FACIAL_HAIR_LOW_RES,
    SECTION_TYPE_HAIR_LOW_RES,
    SECTION_TYPE_UNDERWEAR_LOW_RES,
    SECTION_TYPE_SKIN,
    SECTION_TYPE_FACE,
    SECTION_TYPE_FACIAL_HAIR,
    SECTION_TYPE_HAIR,
    SECTION_TYPE_UNDERWEAR,
    SECTION_TYPE_CUSTOM_DISPLAY_1_LOW_RES,
    SECTION_TYPE_CUSTOM_DISPLAY_1,
    SECTION_TYPE_CUSTOM_DISPLAY_2_LOW_RES,
    SECTION_TYPE_CUSTOM_DISPLAY_2,
    SECTION_TYPE_CUSTOM_DISPLAY_3_LOW_RES,
    SECTION_TYPE_CUSTOM_DISPLAY_3

}
