package com.github.azeroth.dbc.defines;

public enum ItemSpecStat {
    INTELLECT,
    AGILITY,
    STRENGTH,
    SPIRIT,
    HIT,
    DODGE,
    PARRY,
    ONE_HANDED_AXE,
    TWO_HANDED_AXE,
    ONE_HANDED_SWORD,
    TWO_HANDED_SWORD,
    ONE_HANDED_MACE,
    TWO_HANDED_MACE,
    DAGGER,
    FIST_WEAPON,
    GUN,
    BOW,
    CROSSBOW,
    STAFF,
    POLEARM,
    THROWN,
    WAND,
    SHIELD,
    RELIC,
    CRIT,
    HASTE,
    BONUS_ARMOR,
    CLOAK,
    WARGLAIVES,
    RELIC_IRON,
    RELIC_BLOOD,
    RELIC_SHADOW,
    RELIC_FEL,
    RELIC_ARCANE,
    RELIC_FROST,
    RELIC_FIRE,
    RELIC_WATER,
    RELIC_LIFE,
    RELIC_WIND,
    RELIC_HOLY,

    NONE
}
