package com.github.azeroth.dbc.defines;

public enum WorldStateExpressionFunction {
    NONE,
    RANDOM,
    MONTH,
    DAY,
    TIME_OF_DAY,
    REGION,
    CLOCK_HOUR,
    OLD_DIFFICULTY_ID,
    HOLIDAY_START,
    HOLIDAY_LEFT,
    HOLIDAY_ACTIVE,
    TIMER_CURRENT_TIME,
    WEEK_NUMBER,
    UNK13,
    UNK14,
    DIFFICULTY_ID,
    WAR_MODE_ACTIVE,
    UNK17,
    UNK18,
    UNK19,
    UNK20,
    UNK21,
    WORLD_STATE_EXPRESSION,
    KEYSTONE_AFFIX,
    UNK24,
    UNK25,
    UNK26,
    UNK27,
    KEYSTONE_LEVEL,
    UNK29,
    UNK30,
    UNK31,
    UNK32,
    MERSENNE_RANDOM,
    UNK34,
    UNK35,
    UNK36,
    UI_WIDGET_DATA,
    TIME_EVENT_PASSED,

    MAX,
}
