package com.github.mmo.game.quest.enums;

// EnumUtils: DESCRIBE THIS
public enum QuestPushReason {
    Success,    // "Sharing quest with %s..."
    Invalid,    // "%s is not eligible for that quest"
    InvalidToRecipient,    // "%s's attempt to share quest "%s" failed. You are not eligible for that quest."
    Accepted,    // "%s has accepted your quest"
    Declined,    // "%s has declined your quest"
    Busy,    // "%s is busy"
    Dead,    // "%s is dead."
    DeadToRecipient,    // "%s's attempt to share quest "%s" failed. You are dead."
    LogFull,    // "%s's quest log is full"
    LogFullToRecipient,    // "%s's attempt to share quest "%s" failed. Your quest log is full."
    OnQuest,   // "%s is already on that quest"
    OnQuestToRecipient,   // "%s's attempt to share quest "%s" failed. You are already on that quest."
    AlreadyDone,   // "%s has completed that quest"
    AlreadyDoneToRecipient,   // "%s's attempt to share quest "%s" failed. You have completed that quest."
    NotDaily,   // "That quest cannot be shared today"
    TimerExpired,   // "Quest sharing timer has expired"
    NotInParty,   // "You are not in a party"
    DifferentServerDaily,   // "%s is not eligible for that quest today"
    DifferentServerDailyToRecipient,   // "%s's attempt to share quest "%s" failed. You are not eligible for that quest today."
    NotAllowed,   // "That quest cannot be shared"
    Prerequisite,   // "%s hasn't completed all of the prerequisite quests required for that quest."
    PrerequisiteToRecipient,   // "%s's attempt to share quest "%s" failed. You must complete all of the prerequisite quests first."
    LowLevel,   // "%s is too low level for that quest."
    LowLevelToRecipient,   // "%s's attempt to share quest "%s" failed. You are too low level for that quest."
    HighLevel,   // "%s is too high level for that quest."
    HighLevelToRecipient,   // "%s's attempt to share quest "%s" failed. You are too high level for that quest."
    Class,   // "%s is the wrong class for that quest."
    ClassToRecipient,   // "%s's attempt to share quest "%s" failed. You are the wrong class for that quest."
    Race,   // "%s is the wrong race for that quest."
    RaceToRecipient,   // "%s's attempt to share quest "%s" failed. You are the wrong race for that quest."
    LowFaction,   // "%s's reputation is too low for that quest."
    LowFactionToRecipient,   // "%s's attempt to share quest "%s" failed. Your reputation is too low for that quest."
    HighFaction,   // "%s's reputation is too high for that quest."
    HighFactionToRecipient,   // "%s's attempt to share quest "%s" failed. Your reputation is too high for that quest."
    Expansion,   // "%s doesn't own the required expansion for that quest."
    ExpansionToRecipient,   // "%s's attempt to share quest "%s" failed. You do not own the required expansion for that quest."
    NotGarrisonOwner,   // "%s must own a garrison to accept that quest."
    NotGarrisonOwnerToRecipient,   // "%s's attempt to share quest "%s" failed. You must own a garrison to accept that quest."
    WrongCovenant,   // "%s is in the wrong covenant for that quest."
    WrongCovenantToRecipient,   // "%s's attempt to share quest "%s" failed. You are in the wrong covenant for that quest."
    NewPlayerExperience,   // "%s must complete Exile's Reach to accept that quest."
    NewPlayerExperienceToRecipient,   // "%s's attempt to share quest "%s" failed. You must complete Exile's Reach to accept that quest."
    WrongFaction,   // "%s is the wrong faction for that quest."
    WrongFactionToRecipient,   // "%s's attempt to share quest "%s" failed. You are the wrong faction for that quest."
    CrossFactionRestricted,   // "Quests can't be shared in cross-faction groups."
}
