package com.github.mmo.dbc.defines;

public enum ItemEnchantmentType {
    ITEM_ENCHANTMENT_TYPE_NONE,
    ITEM_ENCHANTMENT_TYPE_COMBAT_SPELL,
    ITEM_ENCHANTMENT_TYPE_DAMAGE,
    ITEM_ENCHANTMENT_TYPE_EQUIP_SPELL,
    ITEM_ENCHANTMENT_TYPE_RESISTANCE,
    ITEM_ENCHANTMENT_TYPE_STAT,
    ITEM_ENCHANTMENT_TYPE_TOTEM,
    ITEM_ENCHANTMENT_TYPE_USE_SPELL,
    ITEM_ENCHANTMENT_TYPE_PRISMATIC_SOCKET,
    ITEM_ENCHANTMENT_TYPE_ARTIFACT_POWER_BONUS_RANK_BY_TYPE,
    ITEM_ENCHANTMENT_TYPE_ARTIFACT_POWER_BONUS_RANK_BY_ID,
    ITEM_ENCHANTMENT_TYPE_BONUS_LIST_ID,
    ITEM_ENCHANTMENT_TYPE_BONUS_LIST_CURVE,
    ITEM_ENCHANTMENT_TYPE_ARTIFACT_POWER_BONUS_RANK_PICKER
}
