package com.github.mmo.defines;

// CreatureType.dbc (9.0.2.37176)
public enum CreatureType {
    CREATURE_TYPE_BEAST,
    CREATURE_TYPE_DRAGONKIN,
    CREATURE_TYPE_DEMON,
    CREATURE_TYPE_ELEMENTAL,
    CREATURE_TYPE_GIANT,
    CREATURE_TYPE_UNDEAD,
    CREATURE_TYPE_HUMANOID,
    CREATURE_TYPE_CRITTER,
    CREATURE_TYPE_MECHANICAL,
    CREATURE_TYPE_NOT_SPECIFIED,
    CREATURE_TYPE_TOTEM,
    CREATURE_TYPE_NON_COMBAT_PET,
    CREATURE_TYPE_GAS_CLOUD,
    CREATURE_TYPE_WILD_PET,
    CREATURE_TYPE_ABERRATION
}
