package com.github.mmo.defines;

public enum DiminishingLevels {
    DIMINISHING_LEVEL_1,
    DIMINISHING_LEVEL_2,
    DIMINISHING_LEVEL_3,
    DIMINISHING_LEVEL_IMMUNE,
    DIMINISHING_LEVEL_4,
    DIMINISHING_LEVEL_TAUNT_IMMUNE
}
