package com.github.mmo.defines;

public enum TokenResult {
    TOKEN_RESULT_SUCCESS,
    TOKEN_RESULT_ERROR_DISABLED,
    TOKEN_RESULT_ERROR_OTHER,
    TOKEN_RESULT_ERROR_NONE_FOR_SALE,
    TOKEN_RESULT_ERROR_TOO_MANY_TOKENS,
    TOKEN_RESULT_SUCCESS_NO,
    TOKEN_RESULT_ERROR_TRANSACTION_IN_PROGRESS,
    TOKEN_RESULT_ERROR_AUCTIONABLE_TOKEN_OWNED,
    TOKEN_RESULT_ERROR_TRIAL_RESTRICTED
}
