package com.github.mmo.game.entity.unit.enums;

// byte value (UNIT_FIELD_BYTES_1, 0)
public enum UnitStandStateType {
    UNIT_STAND_STATE_STAND,
    UNIT_STAND_STATE_SIT,
    UNIT_STAND_STATE_SIT_CHAIR,
    UNIT_STAND_STATE_SLEEP,
    UNIT_STAND_STATE_SIT_LOW_CHAIR,
    UNIT_STAND_STATE_SIT_MEDIUM_CHAIR,
    UNIT_STAND_STATE_SIT_HIGH_CHAIR,
    UNIT_STAND_STATE_DEAD,
    UNIT_STAND_STATE_KNEEL,
    UNIT_STAND_STATE_SUBMERGED,
}
