package com.github.azeroth.defines;

public enum ActivateTaxiReply {
    ERR_TAXIOK,
    ERR_TAXIUNSPECIFIEDSERVERERROR,
    ERR_TAXINOSUCHPATH,
    ERR_TAXINOTENOUGHMONEY,
    ERR_TAXITOOFARAWAY,
    ERR_TAXINOVENDORNEARBY,
    ERR_TAXINOTVISITED,
    ERR_TAXIPLAYERBUSY,
    ERR_TAXIPLAYERALREADYMOUNTED,
    ERR_TAXIPLAYERSHAPESHIFTED,
    ERR_TAXIPLAYERMOVING,
    ERR_TAXISAMENODE,
    ERR_TAXINOTSTANDING
}
