package com.github.azeroth.defines;

public enum CharacterUndeleteResult {
    CHARACTER_UNDELETE_RESULT_OK,
    CHARACTER_UNDELETE_RESULT_ERROR_COOLDOWN,
    CHARACTER_UNDELETE_RESULT_ERROR_CHAR_CREATE,
    CHARACTER_UNDELETE_RESULT_ERROR_DISABLED,
    CHARACTER_UNDELETE_RESULT_ERROR_NAME_TAKEN_BY_THIS_ACCOUNT,
    CHARACTER_UNDELETE_RESULT_ERROR_UNKNOWN
}
