package com.github.azeroth.defines;

public enum PartyResult {
    ERR_PARTY_RESULT_OK,
    ERR_BAD_PLAYER_NAME_S,
    ERR_TARGET_NOT_IN_GROUP_S,
    ERR_TARGET_NOT_IN_INSTANCE_S,
    ERR_GROUP_FULL,
    ERR_ALREADY_IN_GROUP_S,
    ERR_NOT_IN_GROUP,
    ERR_NOT_LEADER,
    ERR_PLAYER_WRONG_FACTION,
    ERR_IGNORING_YOU_S,
    ERR_LFG_PENDING,
    ERR_INVITE_RESTRICTED,
    ERR_GROUP_SWAP_FAILED,               // if (PartyOperation == PARTY_OP_SWAP) ERR_GROUP_SWAP_FAILED else ERR_INVITE_IN_COMBAT
    ERR_INVITE_UNKNOWN_REALM,
    ERR_INVITE_NO_PARTY_SERVER,
    ERR_INVITE_PARTY_BUSY,
    ERR_PARTY_TARGET_AMBIGUOUS,
    ERR_PARTY_LFG_INVITE_RAID_LOCKED,
    ERR_PARTY_LFG_BOOT_LIMIT,
    ERR_PARTY_LFG_BOOT_COOLDOWN_S,
    ERR_PARTY_LFG_BOOT_IN_PROGRESS,
    ERR_PARTY_LFG_BOOT_TOO_FEW_PLAYERS,
    ERR_PARTY_LFG_BOOT_NOT_ELIGIBLE_S,
    ERR_RAID_DISALLOWED_BY_LEVEL,
    ERR_PARTY_LFG_BOOT_IN_COMBAT,
    ERR_VOTE_KICK_REASON_NEEDED,
    ERR_PARTY_LFG_BOOT_DUNGEON_COMPLETE,
    ERR_PARTY_LFG_BOOT_LOOT_ROLLS,
    ERR_PARTY_LFG_TELEPORT_IN_COMBAT
}
