package com.github.azeroth.defines;

public enum SheathTypes {
    SHEATHETYPE_NONE,
    SHEATHETYPE_MAINHAND,
    SHEATHETYPE_OFFHAND,
    SHEATHETYPE_LARGEWEAPONLEFT,
    SHEATHETYPE_LARGEWEAPONRIGHT,
    SHEATHETYPE_HIPWEAPONLEFT,
    SHEATHETYPE_HIPWEAPONRIGHT,
    SHEATHETYPE_SHIELD
}
