package com.github.azeroth.defines;

public enum SummonTitle {
    None,
    Pet,
    Guardian,
    Minion,
    Totem,
    Companion,
    RuneBlade,
    Construct,
    Opponent,    // Related to phases and DK prequest line (3.3.5a)
    Vehicle,
    Mount,   // Oculus and Argent Tournament vehicles (3.3.5a)
    LightWell,
    Butler,
    aka,
    Gateway,
    Hatred,
    Statue,
    Spirit,
    WarBanner,
    HeartWarmer,
    HiredBy,
    PurchasedBy,
    Pride,
    TwistedImage,
    NoodleCart,
    InnerDemon,
    Bodyguard,
    Name,
    Squire,
    Champion,
    TheBetrayer,
    EruptingReflection,
    HopelessReflection,
    MalignantReflection,
    WailingReflection,
    Assistant,
    Enforcer,
    Recruit,
    Admirer,
    EvilTwin,
    Greed,
    LostMind,
    ServantOfNZoth
}
