package com.github.azeroth.defines;

import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;

// TotemCategory.dbc (6.0.2.18988)
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public enum TotemCategory {
    TC_SKINNING_SKIFE_OLD(1),
    TC_EARTH_TOTEM(2),
    TC_AIR_TOTEM(3),
    TC_FIRE_TOTEM(4),
    TC_WATER_TOTEM(5),
    TC_COPPER_ROD(6),
    TC_SILVER_ROD(7),
    TC_GOLDEN_ROD(8),
    TC_TRUESILVER_ROD(9),
    TC_ARCANITE_ROD(10),
    TC_MINING_PICK_OLD(11),
    TC_PHILOSOPHERS_STONE(12),
    TC_BLACKSMITH_HAMMER_OLD(13),
    TC_ARCLIGHT_SPANNER(14),
    TC_GYROMATIC_MA(15),
    TC_MASTER_TOTEM(21),
    TC_FEL_IRON_ROD(41),
    TC_ADAMANTITE_ROD(62),
    TC_ETERNIUM_ROD(63),
    TC_HOLLOW_QUILL(81),
    TC_RUNED_AZURITE_ROD(101),
    TC_VIRTUOSO_INKING_SET(121),
    TC_DRUMS(141),
    TC_GNOMISH_ARMY_KNIFE(161),
    TC_BLACKSMITH_HAMMER(162),
    TC_MINING_PICK(165),
    TC_SKINNING_KNIFE(166),
    TC_HAMMER_PICK(167),
    TC_BLADED_PICKAXE(168),
    TC_FLINT_AND_TINDER(169),
    TC_RUNED_COBALT_ROD(189),
    TC_RUNED_TITANIUM_ROD(190),
    TC_RUNED_ELEMENTIUM_ROD(209),
    TC_HIGH_POWERED_BOLT_GUN(210),
    TC_RUNED_COPPER_ROD(230),
    TC_JEWELERS_KIT(238),
    TC_ULTIMATE_GNOMISH_ARMY_KNIFE(250);
    public final int value;
}
