package com.github.azeroth.defines;

public enum TradeStatus {
    PLAYER_BUSY,
    PROPOSED,
    INITIATED,
    CANCELLED,
    ACCEPTED,
    ALREADY_TRADING,
    NO_TARGET,
    UNACCEPTED,
    COMPLETE,
    STATE_CHANGED,
    TOO_FAR_AWAY,
    WRONG_FACTION,
    FAILED,
    PETITION,
    PLAYER_IGNORED,
    STUNNED,
    TARGET_STUNNED,
    DEAD,
    TARGET_DEAD,
    LOGGING_OUT,
    TARGET_LOGGING_OUT,
    RESTRICTED_ACCOUNT,
    WRONG_REALM,
    NOT_ON_TAPLIST,
    CURRENCY_NOT_TRADABLE,
    NOT_ENOUGH_CURRENCY;

}
