package com.github.azeroth.defines;

public enum VoidTransferError {
    VOID_TRANSFER_ERROR_NO_ERROR,
    VOID_TRANSFER_ERROR_INTERNAL_ERROR_1,
    VOID_TRANSFER_ERROR_INTERNAL_ERROR_2,
    VOID_TRANSFER_ERROR_FULL,
    VOID_TRANSFER_ERROR_INTERNAL_ERROR_3,
    VOID_TRANSFER_ERROR_INTERNAL_ERROR_4,
    VOID_TRANSFER_ERROR_NOT_ENOUGH_MONEY,
    VOID_TRANSFER_ERROR_INVENTORY_FULL,
    VOID_TRANSFER_ERROR_ITEM_INVALID,
    VOID_TRANSFER_ERROR_TRANSFER_UNKNOWN
}
