package com.github.azeroth.defines;

import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public enum WorldState {
    WS_CURRENT_PVP_SEASON_ID(3191),
    WS_PREVIOUS_PVP_SEASON_ID(3901),
    WS_TEAM_IN_INSTANCE_ALLIANCE(4485),
    WS_TEAM_IN_INSTANCE_HORDE(4486),
    WS_BATTLEFIELD_WG_VEHICLE_H(3490),
    WS_BATTLEFIELD_WG_MAX_VEHICLE_H(3491),
    WS_BATTLEFIELD_WG_VEHICLE_A(3680),
    WS_BATTLEFIELD_WG_MAX_VEHICLE_A(3681),
    WS_BATTLEFIELD_WG_WORKSHOP_K_W(3698),
    WS_BATTLEFIELD_WG_WORKSHOP_K_E(3699),
    WS_BATTLEFIELD_WG_WORKSHOP_NW(3700),
    WS_BATTLEFIELD_WG_WORKSHOP_NE(3701),
    WS_BATTLEFIELD_WG_WORKSHOP_SW(3702),
    WS_BATTLEFIELD_WG_WORKSHOP_SE(3703),
    WS_BATTLEFIELD_WG_SHOW_TIME_BATTLE_END(3710),
    WS_BATTLEFIELD_WG_TIME_BATTLE_END(3781),
    WS_BATTLEFIELD_WG_SHOW_TIME_NEXT_BATTLE(3801),
    WS_BATTLEFIELD_WG_DEFENDER(3802),
    WS_BATTLEFIELD_WG_ATTACKER(3803),
    WS_BATTLEFIELD_WG_ATTACKED_H(4022),
    WS_BATTLEFIELD_WG_ATTACKED_A(4023),
    WS_BATTLEFIELD_WG_DEFENDED_H(4024),
    WS_BATTLEFIELD_WG_DEFENDED_A(4025),
    WS_BATTLEFIELD_WG_TIME_NEXT_BATTLE(4354),

    WS_BATTLEFIELD_TB_ALLIANCE_CONTROLS_SHOW(5385),
    WS_BATTLEFIELD_TB_HORDE_CONTROLS_SHOW(5384),
    WS_BATTLEFIELD_TB_ALLIANCE_ATTACKING_SHOW(5546),
    WS_BATTLEFIELD_TB_HORDE_ATTACKING_SHOW(5547),

    WS_BATTLEFIELD_TB_BUILDINGS_CAPTURED(5348),
    WS_BATTLEFIELD_TB_BUILDINGS_CAPTURED_SHOW(5349),
    WS_BATTLEFIELD_TB_TOWERS_DESTROYED(5347),
    WS_BATTLEFIELD_TB_TOWERS_DESTROYED_SHOW(5350),

    WS_BATTLEFIELD_TB_FACTION_CONTROLLING(5334), // 1 -> Alliance, 2 -> Horde

    WS_BATTLEFIELD_TB_TIME_NEXT_BATTLE(5332),
    WS_BATTLEFIELD_TB_TIME_NEXT_BATTLE_SHOW(5387),
    WS_BATTLEFIELD_TB_TIME_BATTLE_END(5333),
    WS_BATTLEFIELD_TB_TIME_BATTLE_END_SHOW(5346),

    WS_BATTLEFIELD_TB_STATE_PREPARATIONS(5684),
    WS_BATTLEFIELD_TB_STATE_BATTLE(5344),

    WS_BATTLEFIELD_TB_KEEP_HORDE(5469),
    WS_BATTLEFIELD_TB_KEEP_ALLIANCE(5470),

    WS_BATTLEFIELD_TB_GARRISON_HORDE_CONTROLLED(5418),
    WS_BATTLEFIELD_TB_GARRISON_HORDE_CAPTURING(5419),
    WS_BATTLEFIELD_TB_GARRISON_NEUTRAL(5420), // unused
    WS_BATTLEFIELD_TB_GARRISON_ALLIANCE_CAPTURING(5421),
    WS_BATTLEFIELD_TB_GARRISON_ALLIANCE_CONTROLLED(5422),

    WS_BATTLEFIELD_TB_VIGIL_HORDE_CONTROLLED(5423),
    WS_BATTLEFIELD_TB_VIGIL_HORDE_CAPTURING(5424),
    WS_BATTLEFIELD_TB_VIGIL_NEUTRAL(5425), // unused
    WS_BATTLEFIELD_TB_VIGIL_ALLIANCE_CAPTURING(5426),
    WS_BATTLEFIELD_TB_VIGIL_ALLIANCE_CONTROLLED(5427),

    WS_BATTLEFIELD_TB_SLAGWORKS_HORDE_CONTROLLED(5428),
    WS_BATTLEFIELD_TB_SLAGWORKS_HORDE_CAPTURING(5429),
    WS_BATTLEFIELD_TB_SLAGWORKS_NEUTRAL(5430), // unused
    WS_BATTLEFIELD_TB_SLAGWORKS_ALLIANCE_CAPTURING(5431),
    WS_BATTLEFIELD_TB_SLAGWORKS_ALLIANCE_CONTROLLED(5432),

    WS_BATTLEFIELD_TB_WEST_INTACT_HORDE(5433),
    WS_BATTLEFIELD_TB_WEST_DAMAGED_HORDE(5434),
    WS_BATTLEFIELD_TB_WEST_DESTROYED_NEUTRAL(5435),
    WS_BATTLEFIELD_TB_WEST_INTACT_ALLIANCE(5436),
    WS_BATTLEFIELD_TB_WEST_DAMAGED_ALLIANCE(5437),
    WS_BATTLEFIELD_TB_WEST_INTACT_NEUTRAL(5453), // unused
    WS_BATTLEFIELD_TB_WEST_DAMAGED_NEUTRAL(5454), // unused

    WS_BATTLEFIELD_TB_SOUTH_INTACT_HORDE(5438),
    WS_BATTLEFIELD_TB_SOUTH_DAMAGED_HORDE(5439),
    WS_BATTLEFIELD_TB_SOUTH_DESTROYED_NEUTRAL(5440),
    WS_BATTLEFIELD_TB_SOUTH_INTACT_ALLIANCE(5441),
    WS_BATTLEFIELD_TB_SOUTH_DAMAGED_ALLIANCE(5442),
    WS_BATTLEFIELD_TB_SOUTH_INTACT_NEUTRAL(5455), // unused
    WS_BATTLEFIELD_TB_SOUTH_DAMAGED_NEUTRAL(5456), // unused

    WS_BATTLEFIELD_TB_EAST_INTACT_HORDE(5443),
    WS_BATTLEFIELD_TB_EAST_DAMAGED_HORDE(5444),
    WS_BATTLEFIELD_TB_EAST_DESTROYED_NEUTRAL(5445),
    WS_BATTLEFIELD_TB_EAST_INTACT_ALLIANCE(5446),
    WS_BATTLEFIELD_TB_EAST_DAMAGED_ALLIANCE(5447),
    WS_BATTLEFIELD_TB_EAST_INTACT_NEUTRAL(5451),
    WS_BATTLEFIELD_TB_EAST_DAMAGED_NEUTRAL(5452),

    WS_WAR_MODE_HORDE_BUFF_VALUE(17042),
    WS_WAR_MODE_ALLIANCE_BUFF_VALUE(17043);

    public final int value;
}
